import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const yapariBold = localFont({
  src:[{
    path: './fonts/Yapari-Bold.ttf',
    style: 'bold',
  }],
  variable: "--font-yapari-bold",
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${yapariBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
